import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

export const serverEnv = createEnv({
  server: {
    APP_NAME: z.string().min(1),
    APP_ORIGIN: z.string().min(1),
    APP_ENV: z.union([z.literal("development"), z.literal("production")]),
    DEV_DATABASE_URL: z.string().min(1).url(),
    DEV_DATABASE_MODE: z.union([
      z.literal("default"),
      z.literal("planetscale"),
    ]),
    PROD_DATABASE_URL: z.string().min(1).url(),
    PROD_DATABASE_MODE: z.union([
      z.literal("default"),
      z.literal("planetscale"),
    ]),
    FIREBASE_ADMIN_PROJECT_ID: z.string().min(1),
    FIREBASE_ADMIN_PRIVATE_KEY: z.string().min(1),
    FIREBASE_ADMIN_CLIENT_EMAIL: z.string().min(1).email(),
    RESEND_API_KEY: z.string().min(1),
    MAIL_FROM_URL: z.string().min(1),
    IS_EMAIL_ENABLED: z.union([z.literal("0"), z.literal("1")]),
    SMS_API_URL: z.string().min(1).url(),
    SMS_API_KEY: z.string().min(1),
    IS_SMS_ENABLED: z.union([z.literal("0"), z.literal("1")]),
    GEOAPIFY_API_URL: z.string().min(1).url(),
    GEOAPIFY_API_KEY: z.string().min(1),
    WEB_PUSH_PRIVATE_KEY: z.string().min(1),
    OFFLINE_MODE: z.union([z.literal("0"), z.literal("1")]).optional(),
    EXPO_ACCESS_TOKEN: z.string().min(1),
    SURVEY_URL: z.string().min(1).url(),
    MAPBOX_API_URL: z.string().min(1).url(),
    MAPBOX_SECRET_KEY: z.string().min(1),
    GOOGLE_API_KEY: z.string().min(1),
    AWS_ACCESS_KEY_ID: z.string().min(1),
    AWS_ACCESS_KEY_SECRET: z.string().min(1),
    AWS_SQS_EMAIL_QUEUE_URL: z.string().min(1),
  },
  runtimeEnv: {
    APP_NAME: process.env.APP_NAME,
    APP_ORIGIN: process.env.APP_ORIGIN,
    APP_ENV: process.env.APP_ENV,
    DEV_DATABASE_URL: process.env.DEV_DATABASE_URL,
    DEV_DATABASE_MODE: process.env.DEV_DATABASE_MODE,
    PROD_DATABASE_URL: process.env.PROD_DATABASE_URL,
    PROD_DATABASE_MODE: process.env.PROD_DATABASE_MODE,
    FIREBASE_ADMIN_PROJECT_ID: process.env.FIREBASE_ADMIN_PROJECT_ID,
    FIREBASE_ADMIN_PRIVATE_KEY: process.env.FIREBASE_ADMIN_PRIVATE_KEY,
    FIREBASE_ADMIN_CLIENT_EMAIL: process.env.FIREBASE_ADMIN_CLIENT_EMAIL,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    MAIL_FROM_URL: process.env.MAIL_FROM_URL,
    IS_EMAIL_ENABLED: process.env.IS_EMAIL_ENABLED,
    SMS_API_URL: process.env.SMS_API_URL,
    SMS_API_KEY: process.env.SMS_API_KEY,
    IS_SMS_ENABLED: process.env.IS_SMS_ENABLED,
    GEOAPIFY_API_URL: process.env.GEOAPIFY_API_URL,
    GEOAPIFY_API_KEY: process.env.GEOAPIFY_API_KEY,
    WEB_PUSH_PRIVATE_KEY: process.env.WEB_PUSH_PRIVATE_KEY,
    OFFLINE_MODE: process.env.OFFLINE_MODE,
    EXPO_ACCESS_TOKEN: process.env.EXPO_ACCESS_TOKEN,
    SURVEY_URL: process.env.SURVEY_URL,
    MAPBOX_API_URL: process.env.MAPBOX_API_URL,
    MAPBOX_SECRET_KEY: process.env.MAPBOX_SECRET_KEY,
    GOOGLE_API_KEY: process.env.GOOGLE_API_KEY,
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_ACCESS_KEY_SECRET: process.env.AWS_ACCESS_KEY_SECRET,
    AWS_SQS_EMAIL_QUEUE_URL: process.env.AWS_SQS_EMAIL_QUEUE_URL,
  },
})
