import "@/styles/globals.css"
import { Fonts } from "./fonts"
import { Toaster } from "react-hot-toast"
import { Providers } from "@/providers/providers"
import type { ReactNode } from "react"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <Fonts />
      <Providers>
        <body className="text-brand-black">
          <Toaster position="top-center" />
          {children}
        </body>
      </Providers>
    </html>
  )
}
